# Default values for my-ghost-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4
namespace: default
image:
  repository: httpd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: NodePort
  port: 80

label: web-app